export const Data = [
  {
    id: 1,
    name: "Bhelpuri",
    path: `${process.env.PUBLIC_URL}/assets/foods/bhelpuri.png`,
    isVegan: true,
    category: "fastfood",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 2,
    name: "chicken Biryani",
    path: `${process.env.PUBLIC_URL}/assets/foods/biryani.png`,
    isVegan: false,
    category: "mughlai",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 3,
    name: "Burger",
    path: `${process.env.PUBLIC_URL}/assets/foods/burger.png`,
    isVegan: false,
    category: "fastfood",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 4,
    name: "Chicken Mughlai",
    path: `${process.env.PUBLIC_URL}/assets/foods/chickenkhimamughlai.png`,
    isVegan: false,
    category: "mughlai",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 5,
    name: "Chicken Roll",
    path: `${process.env.PUBLIC_URL}/assets/foods/chickenRoll.png`,
    isVegan: false,
    category: "mughlai",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 6,
    name: "Dosa",
    path: `${process.env.PUBLIC_URL}/assets/foods/dosasouth.png`,
    isVegan: true,
    category: "southIndian",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 7,
    name: "Falahar",
    path: `${process.env.PUBLIC_URL}/assets/foods/falahar.png`,
    isVegan: true,
    category: "dessert",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 8,
    name: "Jalebi",
    path: `${process.env.PUBLIC_URL}/assets/foods/jalebisweet.png`,
    isVegan: true,
    category: "dessert",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 9,
    name: "KFC",
    path: `${process.env.PUBLIC_URL}/assets/foods/kfc.png`,
    isVegan: false,
    category: "fastfood",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 10,
    name: "Ko-Kuck-Ko",
    path: `${process.env.PUBLIC_URL}/assets/foods/ko-kooch-ko.png`,
    isVegan: false,
    category: "northIndian",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 11,
    name: "Burger MC Donald",
    path: `${process.env.PUBLIC_URL}/assets/foods/mcdonaldburger.png`,
    isVegan: false,
    category: "fastfood",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 12,
    name: "Chicken Roast",
    path: `${process.env.PUBLIC_URL}/assets/foods/mughlaiChickenRoast.png`,
    isVegan: false,
    category: "mughlai",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },

  {
    id: 13,
    name: "Paneer Cheese",
    path: `${process.env.PUBLIC_URL}/assets/foods/paneercheesechiinese.png`,
    isVegan: true,
    category: "chinese",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 14,
    name: "Paneer Gravy",
    path: `${process.env.PUBLIC_URL}/assets/foods/paneergravychinese.png`,
    isVegan: true,
    category: "chinese",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 15,
    name: "Paratha",
    path: `${process.env.PUBLIC_URL}/assets/foods/parathanorthindian.png`,
    isVegan: true,
    category: "roti",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 16,
    name: "Pav Bhaji",
    path: `${process.env.PUBLIC_URL}/assets/foods/pavbhaji.png`,
    isVegan: true,
    category: "fastfood",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 17,
    name: "Rasogulla",
    path: `${process.env.PUBLIC_URL}/assets/foods/rasogullabengali.png`,
    isVegan: true,
    category: "dessert",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 18,
    name: "Samosa",
    path: `${process.env.PUBLIC_URL}/assets/foods/samosa.png`,
    isVegan: true,
    category: "fastfood",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 19,
    name: "Sea Food",
    path: `${process.env.PUBLIC_URL}/assets/foods/seafood.png`,
    isVegan: false,
    category: "seafood",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 20,
    name: "Veg Chinese",
    path: `${process.env.PUBLIC_URL}/assets/foods/vegchinese.png`,
    isVegan: true,
    category: "chinese",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 21,
    name: "Momos",
    path: `${process.env.PUBLIC_URL}/assets/foods/vegmomoschinese.png`,
    isVegan: true,
    category: "chinese",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 22,
    name: "Paneer",
    path: `${process.env.PUBLIC_URL}/assets/foods/vegpaneer.png`,
    isVegan: true,
    category: "chinese",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
  {
    id: 23,
    name: "Veg Rice",
    path: `${process.env.PUBLIC_URL}/assets/foods/vegricechinese.png`,
    isVegan: true,
    category: "chinese",
    rating: `${Math.floor(Math.random() * 6)}`,
    price: `${Math.floor(Math.random() * (500 - 100 + 1) + 100)}`,
  },
];
